CUDA backend failed to initialize: Unable to use CUDA because of the following issues with CUDA components:
Outdated cuDNN installation found.
Version JAX was built against: 8906
Minimum supported: 8900
Installed version: 8500
The local installation version must be no lower than 8900. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 149, in broadcast_shapes
    return _broadcast_shapes_cached(*shapes)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/jax/_src/util.py", line 290, in wrapper
    return cached(config.trace_context(), *args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/jax/_src/util.py", line 283, in cached
    return f(*args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 155, in _broadcast_shapes_cached
    return _broadcast_shapes_uncached(*shapes)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 171, in _broadcast_shapes_uncached
    raise ValueError(f"Incompatible shapes for broadcasting: shapes={list(shapes)}")
ValueError: Incompatible shapes for broadcasting: shapes=[(), (480, 1), (468, 468)]

During handling of the above exception, another exception occurred:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/www/shivamp/GODMAX/run_scripts/perlmutter/sample_params_thetaco.py", line 545, in <module>
    traces = pmap(do_mcmc)(rng_keys)
  File "/global/cfs/cdirs/lsst/www/shivamp/GODMAX/run_scripts/perlmutter/sample_params_thetaco.py", line 504, in do_mcmc
    mcmc.run(
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 675, in run
    states, last_state = partial_map_fn(map_args)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 438, in _single_chain_mcmc
    new_init_state = self.sampler.init(
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 749, in init
    init_params = self._init_state(
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 693, in _init_state
    ) = initialize_model(
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/util.py", line 656, in initialize_model
    ) = _get_model_transforms(substituted_model, model_args, model_kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/util.py", line 450, in _get_model_transforms
    model_trace = trace(model).get_trace(*model_args, **model_kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/global/cfs/cdirs/lsst/www/shivamp/GODMAX/run_scripts/perlmutter/sample_params_thetaco.py", line 454, in model
    return numpyro.sample('cl', dist.MultivariateNormal(mu, 
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/distributions/distribution.py", line 99, in __call__
    return super().__call__(*args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/distributions/continuous.py", line 1502, in __init__
    loc, self.covariance_matrix = promote_shapes(loc, covariance_matrix)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/distributions/util.py", line 309, in promote_shapes
    num_dims = len(lax.broadcast_shapes(shape, *shapes))
ValueError: Incompatible shapes for broadcasting: shapes=[(), (480, 1), (468, 468)]
srun: error: nid002429: task 0: Exited with exit code 1
srun: Terminating StepId=27288159.0

real	1m50.810s
user	0m0.037s
sys	0m0.055s
